# Generated by Django 4.0.4 on 2022-05-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('advantages', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('what_we_do', models.CharField(max_length=300)),
                ('desc1', models.TextField()),
                ('logo1', models.ImageField(upload_to='upload')),
                ('mission', models.CharField(max_length=300)),
                ('desc2', models.TextField()),
                ('logo2', models.ImageField(upload_to='upload')),
                ('history', models.CharField(max_length=300)),
                ('desc3', models.TextField()),
                ('logo3', models.ImageField(upload_to='upload')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'о компании',
            },
        ),
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
            ],
            options={
                'verbose_name': 'Категории публикаций',
                'verbose_name_plural': 'категории публикаций',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'цвета',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('service_contains', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
            ],
            options={
                'verbose_name': 'Категории услуг',
                'verbose_name_plural': 'категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password_email', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'информация о пользователе',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
                ('service_types_description', models.CharField(max_length=200)),
                ('offers', models.CharField(max_length=200)),
                ('service_price', models.IntegerField(default=0)),
                ('service_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service_type')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('old_price', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
                ('discount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('author', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog_category')),
            ],
            options={
                'verbose_name': 'Публикации',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
